# Generated by Django 4.0.4 on 2022-05-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listinganimals', '0002_alter_animals_id_alter_breed_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animals',
            new_name='Animal',
        ),
    ]
