# Generated by Django 4.0.4 on 2022-05-20 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listinganimals', '0004_animaldata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animaldata',
            old_name='breedName',
            new_name='breedname',
        ),
    ]
