# Generated by Django 4.0.4 on 2022-05-20 18:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listinganimals', '0005_rename_breedname_animaldata_breedname'),
    ]

    operations = [
        migrations.AddField(
            model_name='animaldata',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
